export const CATEGORY_TIPS = {
  "HVAC":                    "Heating, ventilation, and air conditioning — the mechanical systems that control temperature, humidity, and air quality throughout your home.",
  "Plumbing":                "The network of pipes, fixtures, and appliances that bring fresh water in and carry wastewater out.",
  "Electrical":              "The wiring, circuit breakers, outlets, and fixtures that distribute power safely throughout your home.",
  "Roof":                    "The structure and covering on top of your home that sheds water and protects everything below it.",
  "Gutters & Drainage":      "The channels and pipes that collect rainwater from your roof and direct it safely away from your foundation.",
  "Exterior":                "The outer shell of your home — siding, paint, driveways, decks, and other elements exposed to the weather.",
  "Windows & Doors":         "The openings in your home's envelope, including glass panes, frames, weatherstripping, and hardware.",
  "Garage":                  "The structure and features of your garage, including floors, ventilation, and the door system.",
  "Kitchen":                 "The appliances and fixtures in your kitchen that need regular maintenance to perform well and last longer.",
  "Bathrooms":               "The plumbing fixtures, surfaces, and ventilation in your bathrooms.",
  "Basement & Crawl Space":  "The below-grade areas beneath your home — prone to moisture, pests, and structural issues if neglected.",
  "Laundry":                 "The appliances and ductwork involved in washing and drying clothes.",
  "Yard & Landscaping":      "Your outdoor property — lawn, trees, garden beds, and the equipment that maintains them.",
  "Safety & Security":       "Devices and systems that protect your home and family from fire, gas, intrusion, and other hazards.",
  "Pest Control":            "Preventive measures and inspections to keep insects and rodents out of your home.",
  "Interior":                "The finishes and features inside your home — floors, walls, ceilings, and built-in fixtures.",
};

export const ITEM_TIPS = {
  "Furnace / Air Handler":             "The central unit that heats your home or distributes conditioned air through your ductwork.",
  "Furnace":                           "The heating unit that burns fuel or uses electricity to warm air circulated through your home.",
  "Central Air Conditioner":           "The outdoor compressor and indoor evaporator coil that cool your home by removing heat from the air.",
  "Heat Pump":                         "An all-in-one system that both heats and cools your home by moving heat rather than generating it.",
  "Ductwork":                          "The network of metal or flexible tubes that carry heated or cooled air from your HVAC unit to every room.",
  "Thermostat":                        "The control device that reads your home's temperature and tells your HVAC system when to turn on and off.",
  "Humidifier (whole-home)":           "A device attached to your furnace that adds moisture to the air circulating through your home during dry winter months.",
  "Air Exchanger / HRV":               "A heat recovery ventilator that brings in fresh outdoor air while exhausting stale indoor air, reclaiming heat in the process.",
  "Registers & Vents":                 "The metal grilles in your floors, walls, and ceilings where conditioned air enters and exits each room.",
  "Window / Portable A/C Unit":        "A self-contained air conditioner that sits in a window or on the floor to cool a single room.",
  "Water Heater (Tank)":               "The insulated tank that heats and stores hot water for your home, typically holding 40–80 gallons.",
  "Water Heater (Tankless)":           "An on-demand water heater that heats water instantly as it flows through — no storage tank required.",
  "Water Softener":                    "A system that removes hard minerals from your water to prevent scale buildup in pipes and appliances.",
  "Whole-Home Water Filter":           "A filtration system on your main water line that removes sediment, chlorine, or other contaminants from all water entering your home.",
  "Reverse Osmosis Filter":            "A multi-stage under-sink system that pushes water through a semi-permeable membrane to remove a wide range of contaminants.",
  "Sump Pump":                         "A pump in your basement floor that automatically removes water that collects in a pit, preventing flooding.",
  "Shut-Off Valves":                   "The valves that stop water flow to individual fixtures or to your entire home — essential for emergencies and repairs.",
  "Exposed Pipes":                     "Visible water supply or drain pipes in your basement, utility room, or crawl space.",
  "Outdoor Hose Bibs":                 "The exterior spigots where you attach a garden hose — need to be shut off and drained before winter to prevent freezing.",
  "Irrigation System":                 "The underground network of pipes and sprinkler heads that automatically waters your lawn and garden.",
  "Septic System":                     "An underground tank and drain field that treats and disperses household wastewater on properties not connected to a municipal sewer.",
  "Dishwasher":                        "The appliance that automatically washes and rinses dirty dishes using hot water and detergent.",
  "Refrigerator":                      "The large appliance that keeps food cold by circulating refrigerant through coils to remove heat from inside the cabinet.",
  "Range Hood":                        "The ventilation unit above your stove that captures smoke, steam, and grease and exhausts or filters it.",
  "Gas Range / Cooktop":               "The gas-powered cooking surface with burners that heat pots and pans with an open flame.",
  "Oven":                              "The enclosed cooking compartment that heats food using gas or electric heating elements.",
  "Garbage Disposal":                  "The electrically powered unit under the sink that grinds food waste so it can be flushed through the drain.",
  "Microwave (built-in)":              "A built-in microwave, often installed above the range, that cooks food using microwave radiation and may also vent the cooktop.",
  "Under-Sink Plumbing":               "The supply lines, drain pipes, and P-trap visible under your kitchen sink.",
  "Toilet":                            "The ceramic fixture that uses a tank of water to flush waste through the drain.",
  "Showerhead":                        "The fixture that disperses water for your shower — can accumulate mineral deposits that reduce flow over time.",
  "Shower / Tub Caulk & Grout":        "The waterproof sealant and filler between tiles in your shower or tub surround — prevents water from getting behind the wall.",
  "Exhaust Fan":                       "The ceiling fan in your bathroom that removes humid air to prevent mold and mildew buildup.",
  "Drain":                             "The opening in your sink, tub, or shower floor that carries wastewater down through the pipes.",
  "Vanity Supply Lines":               "The flexible hoses that connect your bathroom faucet and toilet to the water supply shut-off valves.",
  "Smoke Detectors":                   "Life-saving devices that detect smoke from a fire and sound a loud alarm to alert occupants.",
  "Carbon Monoxide Detectors":         "Devices that detect dangerous levels of colorless, odorless carbon monoxide gas produced by combustion appliances.",
  "GFCI Outlets":                      "Ground Fault Circuit Interrupter outlets that instantly cut power if they detect a current leak — required by code near water.",
  "Electrical Panel":                  "The metal box that distributes electricity from the utility line to all the circuits in your home.",
  "Circuit Breakers":                  "The switches inside your electrical panel that automatically trip to cut power when a circuit is overloaded.",
  "Outlets & Switches":                "The wall outlets where you plug in devices and the switches that control lights and ceiling fans.",
  "Exterior Lighting":                 "Light fixtures mounted outside your home for safety, security, and curb appeal.",
  "Surge Protectors":                  "Devices that protect electronics from voltage spikes caused by lightning, utility switching, or large appliances cycling on.",
  "Backup Generator":                  "A gas or propane engine that generates electricity during a power outage to run essential appliances.",
  "Asphalt Shingles":                  "The most common roofing material — overlapping layers of fiberglass mat coated with asphalt and ceramic granules.",
  "Roof Flashing":                     "Thin metal strips installed where the roof meets walls, chimneys, or valleys to prevent water intrusion at the joints.",
  "Roof Vents & Ridge Vents":          "Openings along the roof that allow hot air and moisture to escape from your attic, preventing heat buildup and rot.",
  "Chimney":                           "The masonry or metal structure that channels combustion gases from fireplaces or heating equipment safely to the outside.",
  "Skylights":                         "Windows installed in the roof that bring natural light into your home.",
  "Flat Roof / EPDM":                  "A rubber membrane roofing system commonly used on low-slope or flat roofs.",
  "Gutters":                           "The horizontal channels along the edge of your roofline that collect rainwater as it runs off the roof.",
  "Downspouts":                        "The vertical pipes that carry water from the gutters down to ground level.",
  "Downspout Extensions":              "Attachments at the base of downspouts that direct water farther from the foundation.",
  "Window Wells":                      "Curved metal or plastic barriers around below-grade windows that keep soil back and allow light in.",
  "Yard Grading":                      "The slope of the ground around your home — proper grading directs water away from the foundation.",
  "French Drain / Drain Tile":         "A perforated pipe buried in gravel that collects and redirects groundwater away from your home.",
  "Exterior Paint / Siding":           "The outer covering of your home's walls that protects the structure from moisture, UV, and temperature changes.",
  "Wood Siding / Trim":                "Painted or stained wood boards on the exterior that need periodic refinishing to prevent rot and deterioration.",
  "Fiber Cement / Vinyl Siding":       "Low-maintenance exterior cladding that resists rot, insects, and moisture better than wood.",
  "Brick / Mortar":                    "The fired clay bricks and cement mortar that form a durable exterior wall — mortar can crack and erode over decades.",
  "Foundation":                        "The concrete or masonry base your home sits on — cracks can allow water intrusion or indicate structural settling.",
  "Driveway (asphalt)":                "A paved asphalt surface that needs periodic sealing to prevent cracking from UV and freeze-thaw cycles.",
  "Driveway (concrete)":               "A poured concrete driveway — more durable than asphalt but prone to cracking if left unsealed.",
  "Walkways & Patio":                  "Paved surfaces around your home — concrete, brick, or stone paths that can heave or crack over time.",
  "Deck / Wood Porch":                 "An outdoor platform attached to your home built from wood that requires sealing or staining to prevent rot and weathering.",
  "Composite Deck":                    "An outdoor deck made from a blend of wood fiber and plastic — more rot-resistant than wood but still needs regular cleaning.",
  "Fence (wood)":                      "A wood barrier around your yard that needs periodic staining or sealing to resist moisture and rot.",
  "Retaining Walls":                   "Walls built to hold back soil on a slope — can shift or bow if drainage behind them fails.",
  "Caulking (exterior seams/windows)": "The flexible sealant around window frames, door frames, and exterior joints that keeps out water, drafts, and insects.",
  "Windows":                           "The glass panes and frames that admit light and ventilation while keeping out weather.",
  "Window Screens":                    "Mesh inserts in window frames that keep insects out while allowing airflow.",
  "Exterior Doors":                    "The solid or insulated doors leading to the outside — front door, back door, and side entries.",
  "Storm Doors":                       "A second door installed in front of an exterior door for added insulation and protection from the elements.",
  "Sliding Glass Doors":               "Large glass panels on a track that slide open to connect indoor and outdoor spaces.",
  "Garage Door":                       "The large overhead door that opens and closes the vehicle entrance to your garage.",
  "Garage Door Opener":                "The motorized ceiling unit that automates opening and closing the garage door.",
  "Garage Door Weatherstripping":      "The rubber seals around the edges of the garage door that block drafts, pests, and water.",
  "Basement Walls":                    "The concrete or block walls forming the sides of your basement — can show water seepage or cracks over time.",
  "Crawl Space":                       "The low, unfinished space under your home that houses pipes, wiring, and your home's underbelly.",
  "Dehumidifier":                      "An appliance that removes excess moisture from the air to prevent mold, mildew, and structural damage.",
  "Floor Drain":                       "A drain in the basement floor that catches water from flooding or appliance overflow.",
  "Water Proofing System":             "An interior drainage channel and sump pump system that collects and removes water that enters the basement.",
  "Garage Floor":                      "The concrete slab floor of your garage, often sealed or epoxy-coated to resist stains, moisture, and salt.",
  "Garage Ventilation":                "Vents in the garage walls or ceiling that allow fumes and humidity to escape.",
  "Interior Caulking (tubs, windows)": "The flexible sealant around interior window frames, tubs, and trim that prevents drafts and moisture infiltration.",
  "Hardwood Floors":                   "Natural wood plank floors that can be sanded and refinished to restore their appearance over decades.",
  "Tile Grout":                        "The cement filler between floor or wall tiles — porous and prone to staining and mildew if left unsealed.",
  "Carpet":                            "Soft woven flooring that traps dust, allergens, and odors over time.",
  "Ceiling Fans":                      "Motorized fans mounted on the ceiling that circulate air to help cool a room in summer and push warm air down in winter.",
  "Attic":                             "The space between your top-floor ceiling and the roof — important for insulation, ventilation, and preventing ice dams.",
  "Fireplace (wood-burning)":          "A masonry or prefabricated firebox and chimney system designed to safely burn wood logs indoors.",
  "Gas Fireplace":                     "A fireplace that burns natural gas or propane through a sealed or vented unit for convenient, controllable heat.",
  "Interior Paint":                    "The paint on your interior walls and trim that protects surfaces and refreshes the look of your home.",
  "Door Hinges & Hardware":            "The metal hardware on interior doors — hinges, knobs, and latches — that enable smooth operation.",
  "Staircase":                         "The structure of steps and railings connecting floors, including treads, balusters, and the handrail.",
  "Window Blinds / Shades":            "Window coverings that control light and privacy inside your home.",
  "Dryer":                             "The appliance that removes moisture from wet laundry using heated air tumbled in a rotating drum.",
  "Dryer Vent Duct":                   "The duct that exhausts hot, moist air and lint from your dryer to the outside of your home.",
  "Washing Machine (front-load)":      "A washing machine that loads from the front and uses a tumbling action to clean clothes with less water.",
  "Washing Machine (top-load)":        "A washing machine that loads from the top and uses an agitator or impeller to clean clothes.",
  "Washing Machine Hoses":             "The rubber or braided steel hoses that connect your washing machine to the hot and cold water supply.",
  "Fire Extinguisher":                 "A handheld cylinder containing pressurized extinguishing agent for putting out small fires before they spread.",
  "Security System":                   "A network of sensors, cameras, and a control panel that monitors your home for intrusions.",
  "Door Locks":                        "The lock cylinders and deadbolts on exterior doors that secure your home against entry.",
  "Outdoor Cameras":                   "Video surveillance cameras mounted outside your home that record activity around the perimeter.",
  "Motion-Sensor Lights":              "Exterior lights that turn on automatically when triggered by motion — deters intruders and illuminates entry points.",
  "Radon Detector":                    "A device that measures the concentration of radon, a naturally occurring radioactive gas that can accumulate in lower levels of homes.",
  "Emergency Escape Ladder":           "A portable ladder stored in an upstairs bedroom for safely exiting through a window in a fire emergency.",
  "Foundation & Exterior Seams":       "The gaps, cracks, and seams around your home's foundation and exterior where insects and mice can squeeze through.",
  "Attic & Crawl Space":               "The hidden spaces under your roof and beneath your home that are common nesting sites for rodents and insects.",
  "Termite Prevention":                "Proactive treatment and inspection to guard against termites, which silently eat wood structural members.",
  "Perimeter Treatment":               "A chemical barrier applied around the outside of your home to repel or kill insects before they enter.",
  "Lawn Mower":                        "The gas or electric-powered machine used to cut grass to a consistent height.",
  "Lawn":                              "The grass-covered ground around your home.",
  "Trees":                             "The large woody plants on your property that can pose safety risks if branches become dead or diseased.",
  "Trees & Shrubs":                    "The woody plants on your property that benefit from professional shaping and removal of dead growth.",
  "Garden Beds":                       "The planted areas in your yard containing flowers, shrubs, or ornamental plants.",
  "Outdoor Furniture":                 "Patio chairs, tables, and other outdoor pieces exposed to sun, rain, and seasonal weather.",
  "Pool / Spa":                        "An in-ground or above-ground pool or hot tub used for swimming and relaxation.",
  "Outdoor Gas Grill":                 "A gas-powered outdoor cooking appliance with burners, grates, and a grease collection system.",
};

export const TASK_TIPS = {
  "HVAC|Furnace / Air Handler|Replace air filter":                              "Swap out the dirty air filter with a fresh one. A clogged filter strains your system, reduces airflow, and degrades air quality — it's the single most impactful routine HVAC task.",
  "HVAC|Furnace|Professional inspection & tune-up":                             "A certified technician cleans the burner, checks the heat exchanger for cracks, tests safety controls, and confirms the furnace is running safely and efficiently before heating season.",
  "HVAC|Central Air Conditioner|Professional inspection & tune-up":             "A technician checks refrigerant levels, cleans the coils, inspects electrical connections, and confirms the system is ready to handle cooling season without issues.",
  "HVAC|Central Air Conditioner|Clean condenser coils & fins":                  "The outdoor unit's coils collect dirt and debris that block heat transfer. Rinsing them with a garden hose restores efficiency and prevents the compressor from overheating.",
  "HVAC|Heat Pump|Professional inspection & tune-up":                           "A heat pump serves as both heater and air conditioner, so it should be professionally serviced twice a year — once before heating season and once before cooling season.",
  "HVAC|Ductwork|Inspect for leaks and seal":                                   "Leaky duct joints can waste 20–30% of your conditioned air before it ever reaches a room. Look for gaps at connections and seal them with mastic sealant or metal-backed tape.",
  "HVAC|Ductwork|Professional cleaning":                                        "A professional vacuums and brushes through the full duct system to remove years of accumulated dust, allergens, and debris that degrade air quality.",
  "HVAC|Thermostat|Test functionality / replace batteries":                     "Verify the thermostat reads temperature accurately and triggers heating and cooling as expected. Replace batteries in battery-powered models to avoid unexpected shutdowns in extreme weather.",
  "HVAC|Humidifier (whole-home)|Clean and replace water panel/filter":          "The water panel accumulates mineral scale over the heating season. Replacing it and cleaning the unit prevents mold growth and keeps humidity control accurate.",
  "HVAC|Air Exchanger / HRV|Clean filters and cores":                           "Dirty filters and heat exchange cores restrict airflow and reduce the unit's ability to recover heat. Rinse the filters and wipe down the cores to maintain fresh air flow.",
  "HVAC|Registers & Vents|Vacuum and wipe clean":                               "Dust and debris build up on grilles and restrict airflow to individual rooms. A quick vacuum keeps them clear and reduces airborne allergens.",
  "HVAC|Window / Portable A/C Unit|Clean filter":                               "The filter in a window or portable AC unit traps dust and pet hair. A clogged filter makes the unit work harder, cool less effectively, and consume more electricity.",
  "Plumbing|Water Heater (Tank)|Flush sediment from tank":                      "Minerals from hard water settle at the bottom of the tank over time and insulate the heating element. Flushing through the drain valve removes the buildup and can extend the tank's life by years.",
  "Plumbing|Water Heater (Tank)|Inspect anode rod":                             "The anode rod is a sacrificial metal rod that corrodes so your tank walls don't. Replace it when it's heavily depleted to prevent the tank from rusting from the inside out.",
  "Plumbing|Water Heater (Tankless)|Descale / flush system":                    "Mineral scale builds up inside tankless heaters and restricts water flow and heat transfer. A descaling flush with citric acid or white vinegar solution dissolves the buildup.",
  "Plumbing|Water Softener|Refill salt & clean brine tank":                     "Salt pellets are consumed as the softener regenerates. Refill as needed, and periodically clean the brine tank to break up salt bridges and prevent mushing.",
  "Plumbing|Whole-Home Water Filter|Replace filter cartridge":                  "The filter cartridge removes sediment and contaminants from all water entering your home. A clogged cartridge reduces water pressure and filtration effectiveness throughout the house.",
  "Plumbing|Reverse Osmosis Filter|Replace filters & membrane":                 "The pre-filters, post-filter, and semi-permeable membrane each have a limited lifespan. Replace on schedule to maintain the water quality at your RO drinking tap.",
  "Plumbing|Sump Pump|Test operation & clean pit":                              "Pour a bucket of water into the pit to confirm the float activates the pump and it discharges properly. Clear any silt or debris from the pit that could clog the pump or check valve.",
  "Plumbing|Sump Pump|Replace battery backup":                                  "A dead backup battery means your pump won't run during a storm-related power outage — exactly when you need it most. Batteries lose capacity after 2–3 years even if unused.",
  "Plumbing|Shut-Off Valves|Exercise valves to prevent seizing":                "Valves that sit unused for years can corrode shut and become impossible to close. Turning each valve fully off and back on once a year keeps them operable for emergencies.",
  "Plumbing|Exposed Pipes|Inspect for leaks or corrosion":                      "Look for water stains, rust, mineral deposits, or damp patches around visible pipes. Catching a slow leak or corroded joint early prevents major water damage later.",
  "Plumbing|Outdoor Hose Bibs|Winterize / shut off":                            "Close the interior shut-off valve for each exterior spigot, then open the outdoor faucet to drain any remaining water. Water left in the pipe will freeze and can crack or burst it.",
  "Plumbing|Irrigation System|Winterize (blow out lines)":                      "Use a compressor to force air through each zone, pushing water out of the underground pipes and heads before it freezes and cracks them.",
  "Plumbing|Irrigation System|Spring start-up & leak check":                   "Turn the system on zone by zone, checking each sprinkler head for proper coverage, clogs, or damage from winter frost.",
  "Plumbing|Septic System|Pump and inspect tank":                               "A professional pumps out the accumulated solids from the tank. Skipping this leads to backups, drain field failure, and repairs that can cost thousands.",
  "Plumbing|Septic System|Inspect drain field":                                 "Look for wet spots, unusually lush grass patches, or sewage odors over the drain field — all signs the system is overwhelmed or beginning to fail.",
  "Kitchen|Dishwasher|Clean filter and spray arms":                             "The filter catches food particles and the spray arms jet water onto dishes. Remove both, rinse under running water, and clear any clogged holes in the spray arm with a toothpick.",
  "Kitchen|Dishwasher|Run cleaning cycle with descaler":                        "Mineral deposits and soap scum build up inside the tub and pump over time. A commercial descaler tablet or a cup of white vinegar in an empty hot-water cycle dissolves the buildup.",
  "Kitchen|Refrigerator|Clean condenser coils":                                 "Dusty coils on the back or underside of your fridge make the compressor work harder and can shorten the appliance's lifespan significantly. Vacuum or brush them clean.",
  "Kitchen|Refrigerator|Replace water filter":                                  "The in-door filter removes chlorine and sediment from your ice maker and water dispenser. Replace every six months to maintain water quality and flow rate.",
  "Kitchen|Refrigerator|Check door gaskets for seal":                           "The rubber gasket creates an airtight seal that keeps cold air inside. A worn gasket wastes energy and causes the compressor to run continuously. Test by closing a dollar bill in the door — it should resist being pulled out.",
  "Kitchen|Range Hood|Clean or replace grease filter":                          "The metal mesh filter above your stove captures aerosolized cooking grease. A clogged filter is a fire hazard and reduces the hood's ability to exhaust smoke and fumes.",
  "Kitchen|Gas Range / Cooktop|Clean burner caps and ports":                    "Food and grease clog the small holes in the burner caps that release gas. Use a toothpick or thin wire to clear them and maintain even, full flames.",
  "Kitchen|Gas Range / Cooktop|Inspect gas connections for leaks":              "Check the flexible gas line behind or beneath the range for damage or loose fittings. Apply soapy water to the connections — bubbles forming indicate a gas leak.",
  "Kitchen|Oven|Self-clean cycle / deep clean":                                 "Run the self-cleaning cycle to incinerate baked-on residue, or scrub manually with oven cleaner. A clean oven operates more efficiently and won't produce smoke during cooking.",
  "Kitchen|Garbage Disposal|Clean and deodorize":                               "Grind ice cubes to scrub the grinding ring, then run citrus peels or a disposal cleaner tablet to eliminate odors from trapped food residue inside the unit.",
  "Kitchen|Garbage Disposal|Check for leaks under sink":                        "Inspect the disposal's mounting flange, drain connection, and dishwasher inlet for drips or moisture that could damage the cabinet below.",
  "Kitchen|Microwave (built-in)|Clean grease filter":                           "The aluminum mesh filter behind the vent grille on an over-range microwave captures cooking grease. Rinse it in hot soapy water or run it through the dishwasher.",
  "Kitchen|Under-Sink Plumbing|Inspect for leaks":                              "Open the cabinet and look for moisture, water stains, or active drips from supply lines, the garbage disposal, or the drain trap. Slow leaks can quietly rot the cabinet floor.",
  "Bathrooms|Toilet|Inspect flapper, fill valve & supply line":                 "The flapper is the rubber seal at the bottom of the tank — when it degrades, your toilet runs water continuously. Also check the fill valve cycles properly and the supply line isn't bulging.",
  "Bathrooms|Toilet|Check for base leaks / re-caulk":                           "Staining or softness around the toilet base can indicate a failed wax ring seal. Re-caulk around the base where it meets the floor to prevent moisture from seeping underneath.",
  "Bathrooms|Showerhead|Descale/soak to remove mineral deposits":               "Hard water leaves white mineral deposits that clog the spray holes and reduce pressure. Fill a bag with white vinegar, tie it around the showerhead, and soak overnight to dissolve the buildup.",
  "Bathrooms|Shower / Tub Caulk & Grout|Inspect and re-caulk/re-grout as needed": "Cracked or missing caulk and grout in wet areas lets water get behind the wall, leading to mold growth and expensive structural damage.",
  "Bathrooms|Exhaust Fan|Vacuum and clean fan blades/grille":                   "Dust buildup on the fan blades and cover grille restricts airflow, making the fan less effective at removing humidity after showers — the primary cause of bathroom mold.",
  "Bathrooms|Drain|Clear hair and debris; pour drain cleaner":                  "Hair accumulates in shower and tub drains and eventually causes slow drainage or full clogs. Remove visible debris by hand, then treat with an enzyme drain cleaner.",
  "Bathrooms|Vanity Supply Lines|Inspect hoses for bulging or leaks":           "The braided or rubber hoses under the sink connect the shut-off valve to the faucet. Bulging, cracks, or rust near the fittings are warning signs of an impending burst.",
  "Electrical|Smoke Detectors|Test all units":                                  "Press and hold the test button on each unit until the alarm sounds. A detector that doesn't respond needs new batteries or has reached the end of its service life.",
  "Electrical|Smoke Detectors|Replace batteries":                               "Swap batteries in all battery-powered smoke detectors once a year. A low-battery chirp is the detector warning you — don't wait for it to fail during an actual fire.",
  "Electrical|Smoke Detectors|Replace entire unit":                             "Smoke detectors lose sensitivity as the sensor ages. Replace every unit at 10 years regardless of whether the test button still works — the sensor may no longer reliably detect smoke.",
  "Electrical|Carbon Monoxide Detectors|Test all units":                        "Press the test button to verify the alarm sounds and functions. CO is colorless and odorless, so a malfunctioning detector gives absolutely no warning.",
  "Electrical|Carbon Monoxide Detectors|Replace batteries":                     "Replace batteries annually to ensure the detector stays powered. A dead CO detector is as dangerous as having no detector at all.",
  "Electrical|Carbon Monoxide Detectors|Replace entire unit":                   "The electrochemical sensor inside CO detectors degrades over 5–7 years. Replace the entire unit on schedule even if it still beeps when tested.",
  "Electrical|GFCI Outlets|Test and reset each outlet":                         "Press the 'Test' button to trip the outlet, then 'Reset' to restore power. A GFCI that won't trip or reset has failed and should be replaced by an electrician.",
  "Electrical|Electrical Panel|Visual inspection for corrosion/heat damage":    "Look inside the panel for rust, scorch marks, melted wire insulation, or double-tapped breakers. Any of these signs warrant a call to a licensed electrician.",
  "Electrical|Electrical Panel|Professional inspection":                        "A licensed electrician tests the panel's capacity, checks for code violations, and verifies all connections are tight — typically needed every decade or after major renovations.",
  "Electrical|Circuit Breakers|Exercise breakers to prevent seizing":           "Flip each breaker fully off then back on once a year. Breakers that never move can corrode in place and lose the ability to trip when a circuit is overloaded.",
  "Electrical|Outlets & Switches|Check for loose covers; test functionality":   "Walk through the home and verify each outlet and switch works. Check that cover plates are secure and that nothing feels warm to the touch — warmth indicates a wiring problem.",
  "Electrical|Exterior Lighting|Replace bulbs; clean fixtures":                 "Check that all exterior lights are working — a burned-out front light is a security and safety hazard. Wipe down fixtures to remove accumulated dirt and spider webs.",
  "Electrical|Surge Protectors|Replace units":                                  "Surge protectors degrade silently after absorbing voltage spikes from lightning or appliances. Replace every 2–3 years even if the indicator light still shows 'protected.'",
  "Electrical|Backup Generator|Test run and oil change":                        "Run the generator under load for 20–30 minutes to confirm it starts and produces power. Change the oil per the manufacturer's schedule to prevent engine wear during extended use.",
  "Roof|Asphalt Shingles|Visual inspection for missing/damaged shingles":       "Walk around your home and look up at the roof for missing, curling, cracking, or blistering shingles. Damaged shingles let water reach the wood decking underneath.",
  "Roof|Roof Flashing|Inspect for lifting, rust or gaps":                       "Flashing seals the joints where the roof meets walls, chimneys, and valleys. Lifted or corroded flashing is one of the most common causes of roof leaks.",
  "Roof|Roof Vents & Ridge Vents|Inspect for blockages":                        "Check that vent openings are clear of debris, bird nests, and ice dams. Blocked vents trap heat and moisture in the attic, accelerating the deterioration of the roof deck.",
  "Roof|Chimney|Inspect cap, crown, flashing & mortar":                         "Check that the cap (keeps rain out), crown (concrete top slab), and flashing are intact, and that mortar joints between the bricks are solid — all are entry points for water.",
  "Roof|Chimney|Professional sweep / cleaning":                                 "A chimney sweep removes creosote — a highly flammable byproduct of burning wood — from the flue lining. Required annually if you use your fireplace regularly.",
  "Roof|Skylights|Inspect seals and clean glass":                               "Check the caulk and flashing around the skylight frame for cracking. Condensation between the glass panes indicates a failed seal — the unit needs replacement.",
  "Roof|Flat Roof / EPDM|Inspect membrane and seams":                           "Walk the roof and check the rubber membrane for punctures, tears, and open seams. Water pools on flat roofs, so even small gaps can lead to significant interior leaks.",
  "Gutters & Drainage|Gutters|Clear leaves and debris":                         "Blocked gutters can't carry rainwater away, causing overflow that can seep behind fascia boards, saturate the soil at the foundation, or cause basement water intrusion.",
  "Gutters & Drainage|Gutters|Inspect for sagging, cracks or leaks":            "Check that gutters are pitched correctly and firmly attached to the fascia. Sagging sections hold standing water and eventually leak at the seams.",
  "Gutters & Drainage|Downspouts|Flush and confirm clear flow":                 "Run a hose into the top of each downspout to verify water flows freely to the bottom. A blockage causes the gutters above to overflow at the nearest joint.",
  "Gutters & Drainage|Downspout Extensions|Direct water 4–6 ft from foundation": "Extensions at the base of downspouts ensure water exits well away from the house rather than pooling against the foundation wall.",
  "Gutters & Drainage|Window Wells|Clear debris and check drainage":            "Debris-filled window wells can hold water that seeps through basement windows. Check that the gravel layer at the bottom drains freely.",
  "Gutters & Drainage|Yard Grading|Inspect slope away from foundation":         "The ground around your home should slope downward and away from the foundation. Flat or inward-sloping soil allows rainwater to saturate the ground next to your basement walls.",
  "Gutters & Drainage|French Drain / Drain Tile|Inspect outlets and flow":      "Check that the outlet pipe at the low end of the drain is unobstructed. A blocked outlet defeats the purpose of the drain and may cause water to back up.",
  "Exterior|Exterior Paint / Siding|Inspect for peeling, cracking or rot":      "Walk around your home and look for peeling paint, cracked siding, or soft, discolored wood — early signs of rot. Exposed wood deteriorates quickly once the protective coating fails.",
  "Exterior|Wood Siding / Trim|Re-paint or re-stain as needed":                 "Fresh paint or stain is the primary defense against moisture and rot. Repaint when the existing finish is chalking, peeling, or worn through.",
  "Exterior|Fiber Cement / Vinyl Siding|Pressure wash and inspect":             "Mold, mildew, and dirt accumulate on siding over time. A pressure wash restores appearance and reveals loose panels, cracks, or holes.",
  "Exterior|Brick / Mortar|Inspect for cracks and tuckpoint":                   "Mortar joints erode over decades. Tuckpointing fills deteriorated joints with fresh mortar to restore the watertight integrity of brick walls.",
  "Exterior|Foundation|Walk perimeter; inspect for cracks":                     "Hairline cracks in poured concrete are common and usually benign. Horizontal cracks in block walls or wide stair-step cracks signal potential structural movement that warrants professional evaluation.",
  "Exterior|Driveway (asphalt)|Seal coat":                                      "A fresh layer of sealant fills micro-cracks and protects asphalt from water infiltration, UV oxidation, and freeze-thaw damage that causes crumbling.",
  "Exterior|Driveway (concrete)|Seal cracks and apply concrete sealer":         "Fill cracks with concrete filler and apply a penetrating sealer to repel water, de-icing salt, and staining that weakens the surface over time.",
  "Exterior|Walkways & Patio|Inspect for cracks and heaving":                   "Tree roots, frost heave, and soil settling can lift or crack paved surfaces. Raised edges create trip hazards and wide cracks allow water to undermine the base.",
  "Exterior|Deck / Wood Porch|Clean and re-stain or seal":                      "Wood that grays and splinters is losing its protection. A fresh coat of stain or sealer applied after cleaning restores water resistance and extends the deck's life significantly.",
  "Exterior|Deck / Wood Porch|Inspect boards and fasteners for rot":            "Press a screwdriver into boards and posts — soft spots mean the wood is rotting. Also check that screws and ledger bolts are tight and not corroding through.",
  "Exterior|Composite Deck|Clean with deck cleaner":                            "Composite decking accumulates mold, mildew, and dirt in the groove patterns. A composite-specific deck cleaner removes buildup without damaging the material.",
  "Exterior|Fence (wood)|Inspect posts; re-stain or seal":                      "Fence posts rot from the bottom up where they contact soil. Check for wobble or soft spots at ground level, then re-stain or seal the boards to prevent further weathering.",
  "Exterior|Retaining Walls|Inspect for bowing or drainage issues":             "A bowing or leaning wall is under pressure from water-saturated soil. Check that weep holes are open so water can drain through rather than build up behind the wall.",
  "Exterior|Caulking (exterior seams/windows)|Inspect and re-caulk gaps":       "Caulk around window frames, door frames, and utility penetrations shrinks and cracks over time. Fresh caulk keeps air, water, and insects out and reduces heating and cooling costs.",
  "Windows & Doors|Windows|Clean tracks, lubricate hardware":                   "Dirt in tracks makes windows hard to open and close. Clean with a vacuum and brush, then apply silicone lubricant to hinges and locking hardware.",
  "Windows & Doors|Windows|Inspect weatherstripping and seals":                 "Worn weatherstripping around the frame allows cold air in and conditioned air out. Replace if compressed, torn, or missing to maintain comfort and reduce energy bills.",
  "Windows & Doors|Window Screens|Inspect and repair tears":                    "Small tears in screens let insects in while you're trying to ventilate. Repair kits are inexpensive and easy to use, or replace the mesh entirely for large damage.",
  "Windows & Doors|Exterior Doors|Inspect weatherstripping and threshold":      "The seal between the door and frame prevents drafts and water infiltration. A visible gap or daylight around a closed door means the weatherstripping needs replacement.",
  "Windows & Doors|Exterior Doors|Lubricate hinges and deadbolts":              "Apply dry lubricant or graphite powder to door hinges and lock cylinders. Stiff locks and squeaky hinges are minor now but can become impossible to operate over time.",
  "Windows & Doors|Storm Doors|Clean and adjust door closer":                   "Clean the glass panels and hardware, then adjust the pneumatic closer so the door latches fully without slamming — a door that doesn't latch fully provides no weather protection.",
  "Windows & Doors|Sliding Glass Doors|Clean and lubricate track":              "Clean dirt and debris from the track so the door glides smoothly. Apply silicone spray to the track and rollers — a sticky door accelerates wear on the rollers.",
  "Windows & Doors|Garage Door|Lubricate springs, rollers and tracks":          "Apply dedicated garage door lubricant (not WD-40) to the torsion springs, hinges, and rollers. Lubricated parts operate quietly, move smoothly, and last longer.",
  "Windows & Doors|Garage Door|Test auto-reverse safety feature":               "Place a 2x4 flat on the ground under the door. When the door contacts it while closing, it should automatically reverse. A door that doesn't reverse is a serious safety risk.",
  "Windows & Doors|Garage Door Opener|Replace backup battery":                  "The backup battery lets you open the garage door when the power is out. Replace annually — during an outage, a dead backup battery means you're stuck.",
  "Windows & Doors|Garage Door Weatherstripping|Inspect and replace bottom seal": "The rubber bottom seal blocks drafts, pests, and water. Replace it when cracked, compressed flat, or torn to maintain the seal between the door and the floor.",
  "Basement & Crawl Space|Basement Walls|Inspect for water intrusion or efflorescence": "Efflorescence is the white powdery residue left when water moves through concrete and evaporates — it signals ongoing moisture infiltration that can eventually cause structural damage.",
  "Basement & Crawl Space|Crawl Space|Inspect vapor barrier and insulation":    "The plastic sheeting on the crawl space floor prevents ground moisture from entering the structure. Check for tears, gaps, and verify the insulation between the floor joists is intact and dry.",
  "Basement & Crawl Space|Dehumidifier|Empty reservoir; clean filter":          "During humid months a basement dehumidifier can fill its reservoir quickly. Empty it regularly (or use a drain hose) and rinse the air filter to maintain efficiency.",
  "Basement & Crawl Space|Floor Drain|Pour water to maintain trap seal":        "If a floor drain sits unused for months, the water in its P-trap evaporates — allowing sewer gases to seep into your basement. Pour a cup of water to keep the trap sealed.",
  "Basement & Crawl Space|Water Proofing System|Inspect drains and pump":       "Check that the interior drain channel is free of debris and that the sump pump activates and discharges properly. A failed waterproofing system can flood your basement in hours.",
  "Garage|Garage Floor|Seal concrete or touch up epoxy":                        "Sealing or epoxy-coating the garage floor protects concrete from oil stains, moisture, freeze-thaw spalling, and the road salt that gets tracked in from vehicles.",
  "Garage|Garage Ventilation|Clear vents of obstructions":                      "Proper garage ventilation removes vehicle exhaust fumes, reduces moisture buildup, and prevents the space from overheating. Check that vents aren't blocked by storage items.",
  "Interior|Interior Caulking (tubs, windows)|Inspect and re-apply where needed": "Caulk around bathtubs, showers, and window frames cracks and shrinks over time. Re-caulking prevents water infiltration and keeps the finished surfaces looking clean.",
  "Interior|Hardwood Floors|Clean and apply polish/refresh coat":               "Hardwood floors lose their protective finish under years of foot traffic. Apply a compatible polish to refresh protection, or for deeper wear, have them professionally sanded and refinished.",
  "Interior|Tile Grout|Clean and re-seal grout lines":                          "Grout is porous and absorbs stains and moisture if left unsealed. Scrub with a grout brush, then apply a penetrating sealer to restore protection and prevent mildew.",
  "Interior|Carpet|Professional steam clean":                                   "Professional hot-water extraction removes embedded dirt, allergens, pet dander, and odors that regular vacuuming can't reach, and revives compressed pile.",
  "Interior|Ceiling Fans|Reverse direction seasonally; clean blades":           "In winter, switch to clockwise rotation on low speed to push warm air down from the ceiling. In summer, counterclockwise creates a cooling breeze. Wipe the blades to remove dust buildup.",
  "Interior|Attic|Inspect insulation and ventilation for moisture":             "Look for compressed, missing, or wet insulation and for condensation on the roof deck. Poor attic ventilation leads to ice dams in winter, mold, and inflated energy bills year-round.",
  "Interior|Fireplace (wood-burning)|Sweep and inspect":                        "A chimney sweep removes creosote from the flue and inspects the firebox, damper, and liner for cracks or deterioration. Required annually before the burning season.",
  "Interior|Gas Fireplace|Clean glass and test ignition":                       "Wipe the white haze from the glass panel caused by combustion byproducts, vacuum the firebox, and verify the igniter and pilot light work reliably before the season.",
  "Interior|Interior Paint|Touch up walls and trim":                            "Touch up scuffs, nail holes, and worn trim with matching paint to protect the surface underneath and keep the interior looking well-maintained.",
  "Interior|Door Hinges & Hardware|Lubricate squeaky hinges":                   "A drop of 3-in-1 oil or dry lubricant on door hinge pins eliminates squeaks and prevents the hinge from wearing unevenly over time.",
  "Interior|Staircase|Tighten balusters and check treads":                      "Loose balusters (the vertical posts in the railing) are a fall hazard. Tighten any that wobble and confirm that no treads are cracked or pulling loose from the stringers.",
  "Interior|Window Blinds / Shades|Dust and clean":                            "Blinds and shades collect dust that degrades indoor air quality and can eventually stain fabric shades. Wipe slats with a damp cloth or use a purpose-made blind duster.",
  "Laundry|Dryer|Clean lint trap":                                              "A full lint trap restricts airflow, dramatically lengthens drying time, and is a leading cause of house fires. Clean it before every single load — it takes five seconds.",
  "Laundry|Dryer Vent Duct|Clean full duct run":                                "Lint accumulates through the entire duct run from the dryer to the exterior cap. A clogged duct is a serious fire hazard and can double or triple drying time.",
  "Laundry|Washing Machine (front-load)|Run drum-clean cycle; wipe door seal":  "The rubber gasket around the door traps moisture and becomes a breeding ground for mold. Wipe it dry after each use and run a monthly drum-clean cycle with a machine cleaner tablet.",
  "Laundry|Washing Machine (top-load)|Run self-clean cycle":                    "Detergent residue, fabric softener, and mineral deposits build up inside the drum and create odors that transfer to your laundry. Run the 'tub clean' cycle monthly.",
  "Laundry|Washing Machine Hoses|Inspect hoses for bulging or cracks":          "A burst washing machine hose can flood your home with hundreds of gallons in minutes. Replace rubber hoses every 5 years and upgrade to braided steel hoses for significantly better protection.",
  "Safety & Security|Fire Extinguisher|Check pressure gauge":                   "The needle on the pressure gauge should point to the green zone. A low-pressure extinguisher won't work in a fire and needs to be recharged or replaced immediately.",
  "Safety & Security|Fire Extinguisher|Professional inspection / recharge":     "A certified technician confirms the extinguisher is fully charged, the tamper seal is intact, and the unit is in proper working condition for its rated fire class.",
  "Safety & Security|Security System|Test all sensors and keypad":              "Trigger each door and window sensor while watching the keypad display, then test the motion detectors. Any sensor that doesn't register leaves a gap in your coverage.",
  "Safety & Security|Door Locks|Lubricate lock cylinders":                      "Insert powdered graphite or dry lubricant spray into the keyhole to keep the cylinder turning smoothly. Locks that stiffen gradually can eventually become impossible to operate.",
  "Safety & Security|Outdoor Cameras|Clean lenses; check angles":               "Wipe camera lenses clean of dust, spider webs, and moisture. Also confirm each camera is still aimed at its intended coverage area — cameras can shift after wind or vibration.",
  "Safety & Security|Motion-Sensor Lights|Test and replace bulbs":              "Walk through each light's detection zone to verify it activates. Replace burned-out bulbs so the lights work when you actually need them for safety or deterrence.",
  "Safety & Security|Radon Detector|Test radon levels":                         "Radon is the second leading cause of lung cancer in the US. Test with a long-term detector or a short-term kit, and investigate mitigation if levels reach or exceed 4 pCi/L.",
  "Safety & Security|Emergency Escape Ladder|Inspect condition and practice use": "Check the ladder for corrosion, broken hooks, and frayed straps. Practice deploying it from the window so you're not fumbling with it for the first time in a real emergency.",
  "Pest Control|Foundation & Exterior Seams|Seal cracks and gaps (pest exclusion)": "Insects and mice can squeeze through surprisingly small gaps. Fill openings around pipes, cables, and foundation cracks with caulk, foam sealant, or hardware cloth.",
  "Pest Control|Attic & Crawl Space|Inspect for rodent droppings or nests":     "Look for droppings, gnawed wood, and nesting material — signs of active rodent presence. Early detection limits structural damage and prevents a small problem from becoming an infestation.",
  "Pest Control|Termite Prevention|Professional termite inspection":             "Termites can hollow out structural lumber for years before any visible damage appears. Annual inspection by a trained professional is the most reliable way to catch them early.",
  "Pest Control|Perimeter Treatment|Apply pest control barrier":                "A liquid or granular pesticide applied around the perimeter creates a chemical barrier that kills or repels ants, spiders, and other insects before they can enter your home.",
  "Yard & Landscaping|Lawn Mower|Sharpen blade, change oil & air filter":       "A sharp mower blade cuts grass cleanly, reducing stress on the lawn. Fresh oil and a clean air filter keep the engine running efficiently throughout the whole mowing season.",
  "Yard & Landscaping|Lawn|Aerate and overseed":                                "Aeration punches small holes in compacted soil to let water, air, and nutrients reach the roots. Overseeding immediately after fills in thin or bare patches before winter dormancy.",
  "Yard & Landscaping|Lawn|Fertilize":                                          "Apply a balanced lawn fertilizer on schedule to supply the nitrogen, phosphorus, and potassium that grass needs to stay thick, green, and resistant to weeds.",
  "Yard & Landscaping|Trees|Inspect for dead/hazardous branches":               "Dead or weakly attached branches can fall without warning and damage property or injure people. Look for leafless branches, cracks at the union, or fungal growth on the bark.",
  "Yard & Landscaping|Trees & Shrubs|Professional trimming":                    "An arborist or landscaper shapes trees and shrubs to promote healthy growth, remove crossing branches, and maintain safe clearance from the house, roof, and power lines.",
  "Yard & Landscaping|Garden Beds|Mulch refresh to 2–3 in depth":              "Fresh mulch suppresses weeds, retains soil moisture, regulates soil temperature, and gives the beds a clean, finished appearance.",
  "Yard & Landscaping|Outdoor Furniture|Clean and apply UV protector":          "Wash away winter grime and apply UV-protective spray or oil to prevent fading, cracking, and brittleness from extended sun exposure.",
  "Yard & Landscaping|Pool / Spa|Balance chemicals":                            "Test pH, alkalinity, and sanitizer levels and adjust as needed. Unbalanced water is unsafe to swim in and causes corrosion of surfaces, fittings, and equipment.",
  "Yard & Landscaping|Pool / Spa|Winterize":                                    "Lower the water level, blow out and drain all plumbing lines, add winterizing chemicals, and cover the pool to protect it from ice damage through the off-season.",
  "Yard & Landscaping|Outdoor Gas Grill|Clean burners and grates":              "Remove the grates and burner covers and brush off grease and carbon buildup. Clogged burner ports cause uneven heat distribution and are a fire hazard.",
};
